name: C MESON CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Update & clean system
      run: sudo apt update && sudo apt upgrade && sudo apt autoremove --purge
    - name: Enable Sources Repo
      run: sudo sed -i '/deb-src/s/^# //' /etc/apt/sources.list && sudo apt update
    - name: install deps
      run: sudo apt build-dep gnome-recipes
    - name: clean build
      run: rm -rf build
    - name: meson prefix --init
      run: meson --prefix /usr build
    - name: ninja build
      run: ninja -C build
